# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d124acd1215c83d630f63192128d8f2ff7e77bcbc03acf44b91a9ff3fbbd45583a30b9595a327d252afbefc52069f9c8a33e68cef82bcae8a61b829808a655f2

test:
  secret_key_base: 64597eae8208e2289b76ec0bff9bae4ace49b7f50ffebceea1ab698d1cb12726638d5de23a28c0a68b473b1d61c190a94a375c2306f488d3f552b9bc0ddac967

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
